/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as LegalAssetsIndexRouteImport } from './routes/legal-assets.index'
import { Route as QuemSomosMissaoVisaoValoresRouteImport } from './routes/quem-somos.missao-visao-valores'
import { Route as QuemSomosNossaHistoriaRouteImport } from './routes/quem-somos.nossa-historia'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesSlugRouteImport } from './routes/solucoes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAssetsIndexRoute = LegalAssetsIndexRouteImport.update({
  id: '/legal-assets/',
  path: '/legal-assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosMissaoVisaoValoresRoute =
  QuemSomosMissaoVisaoValoresRouteImport.update({
    id: '/missao-visao-valores',
    path: '/missao-visao-valores',
    getParentRoute: () => QuemSomosRoute,
  } as any)
const QuemSomosNossaHistoriaRoute = QuemSomosNossaHistoriaRouteImport.update({
  id: '/nossa-historia',
  path: '/nossa-historia',
  getParentRoute: () => QuemSomosRoute,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSlugRoute = SolucoesSlugRouteImport.update({
  id: '/solucoes/$slug',
  path: '/solucoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/missao-visao-valores': typeof QuemSomosMissaoVisaoValoresRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/legal-assets/': typeof LegalAssetsIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/missao-visao-valores': typeof QuemSomosMissaoVisaoValoresRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/legal-assets': typeof LegalAssetsIndexRoute
  '/solucoes': typeof SolucoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/missao-visao-valores': typeof QuemSomosMissaoVisaoValoresRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/legal-assets/': typeof LegalAssetsIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quem-somos'
    | '/quem-somos/missao-visao-valores'
    | '/quem-somos/nossa-historia'
    | '/solucoes/$slug'
    | '/legal-assets/'
    | '/solucoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quem-somos'
    | '/quem-somos/missao-visao-valores'
    | '/quem-somos/nossa-historia'
    | '/solucoes/$slug'
    | '/legal-assets'
    | '/solucoes'
  id:
    | '__root__'
    | '/'
    | '/quem-somos'
    | '/quem-somos/missao-visao-valores'
    | '/quem-somos/nossa-historia'
    | '/solucoes/$slug'
    | '/legal-assets/'
    | '/solucoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuemSomosRoute: typeof QuemSomosRouteWithChildren
  SolucoesSlugRoute: typeof SolucoesSlugRoute
  LegalAssetsIndexRoute: typeof LegalAssetsIndexRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-assets/': {
      id: '/legal-assets/'
      path: '/legal-assets'
      fullPath: '/legal-assets/'
      preLoaderRoute: typeof LegalAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/missao-visao-valores': {
      id: '/quem-somos/missao-visao-valores'
      path: '/missao-visao-valores'
      fullPath: '/quem-somos/missao-visao-valores'
      preLoaderRoute: typeof QuemSomosMissaoVisaoValoresRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/quem-somos/nossa-historia': {
      id: '/quem-somos/nossa-historia'
      path: '/nossa-historia'
      fullPath: '/quem-somos/nossa-historia'
      preLoaderRoute: typeof QuemSomosNossaHistoriaRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$slug': {
      id: '/solucoes/$slug'
      path: '/solucoes/$slug'
      fullPath: '/solucoes/$slug'
      preLoaderRoute: typeof SolucoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuemSomosRouteChildren {
  QuemSomosMissaoVisaoValoresRoute: typeof QuemSomosMissaoVisaoValoresRoute
  QuemSomosNossaHistoriaRoute: typeof QuemSomosNossaHistoriaRoute
}

const QuemSomosRouteChildren: QuemSomosRouteChildren = {
  QuemSomosMissaoVisaoValoresRoute: QuemSomosMissaoVisaoValoresRoute,
  QuemSomosNossaHistoriaRoute: QuemSomosNossaHistoriaRoute,
}

const QuemSomosRouteWithChildren = QuemSomosRoute._addFileChildren(
  QuemSomosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuemSomosRoute: QuemSomosRouteWithChildren,
  SolucoesSlugRoute: SolucoesSlugRoute,
  LegalAssetsIndexRoute: LegalAssetsIndexRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
